---
# Documentation: https://sourcethemes.com/academic/docs/managing-content/

title: "IFPT 2019"
subtitle: ""
summary: "China has their own Post-Quantum Cryptography Standard"
authors: [cothan]
tags: []
categories: []
date: 2020-02-25T21:23:51-04:00
lastmod: 2020-02-25T21:23:51-04:00
featured: false
draft: false

# Featured image
# To use, add an image named `featured.jpg/png` to your page's folder.
# Focal points: Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight.
image:
  caption: ""
  focal_point: ""
  preview_only: false

# Projects (optional).
#   Associate this post with one or more of your projects.
#   Simply enter your project's folder or file name without extension.
#   E.g. `projects = ["internal-project"]` references `content/project/deep-learning/index.md`.
#   Otherwise, set `projects = []`.
projects: []
---

== Tianjin

- Attending FPT conference, where a lot of papers in FPGA technique will become obsolete when the transistor size decreases. (meaning the resources in FPGA become double, turn out, no reason to spend extra work to save 30% resources of smaller FPGA board which is only 5% of new FPGA board.)

- A lot, lot of papers about Improving Machine Learning in term of speed, accuracy. The takeaway thing is there are libraries from big vendors handle all such things. No need to reinvent the wheel.

- FPGA is now friendlier, like GPU cards, where people can plug in and play, it will give less performance compared to GPU, but for the new learning model, architectures, FPGA is way way better than GPU or fixed ASIC designs.

- A lot of friends I hang out with have no plan to publish their research source code. Make the community is not so engineering friendly, as a result, without the source code to play with, I barely care about what they're doing or to apply their research to mine.

- The conference is so deep in the field, yes, people barely care about my research, or to other research not in their field. They walk out when the talk topic changes.

- The auto-car driving startup in China is amazing, super amazing, as a point of view compares to US, they are approaching auto-driving state similar speed to US. Tesla took at least 10 years to have their cars run on the street hand-off eyes-off. Startup in China took 5 years to build a running car with hand-off eyes-on. They have car factories, like every car components can be manufactured in China, which makes the auto-driving startup in China grow super fast.

- A Chinese startup revealed they receive millions of dollars to replace all taxi cabs with driverless taxi cabs, the surprising thing is not about they receive millions of dollars, but the push for driverless cars is too strong.


== Beijing


- Food is okay. Salty.

- Chinese are like Vietnamese, but with an DLC package, richer, including better inner-city transportation.

- Political talk in China is a very scary subject. We have dinner in the private room with Tsinghua (top #1 in China), when it comes to political talks, people often look at the closed door then start talking. Free speak here is somewhat stricter than Vietnam.

- I learn that average Chinese engineers are better than average US engineers. They just don't use English.

== Crypto talk in Tsinghua University


- My professor presents the process of benchmarking PQC candidates. We received a bunch of questions from hardware start-up PhD, master student, some are good questions, some want to embed PQC security to market as soon as possible (like start-up in US).

- There is Post-Quantum Cryptography Competition in China, they want to create their own Chinese standard, but the process is somewhat faster compared to US, the competition is kinda unknown to the rest of the world. My reaction is like, wtf are they doing with the crypto ?

- NIST PQC had only 01 submissions from China. Yes, US eliminated a lot of submissions from China.

- China PQC has all submissions from China, seem like no country else participates in their standardized process.

